name: Clean Old Releases

on:
    release:
        types: [published]

permissions:
    contents: write

jobs:
    clean:
        runs-on: ubuntu-latest
        steps:
            - uses: nikhilbadyal/ghaction-rm-releases@v0.8.0
              with:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  RELEASE_PATTERN: "Release*"
                  RELEASES_TO_KEEP: 1
